### ISSUE TITLE
Previewer: Unnecessary horizontal scrollbars

### ISSUE THREAD

**Issue by youknowriad** [WordPress/wporg-theme-directory#140]
**Describe the bug**

If you have "scrollbars always visible" enabled on MacOS (or in Windows I'm guessing), you'll see horizontal scrollbars in the sidebar of the previewer. 

Also, a black border is visible at the right of the sidebar which seems unnecessary.

**To Reproduce**

- Enable "scrollbars always visible" on MacOs settings.
- Open https://wordpress.org/themes/twentytwentyfour/preview/

**Expected behavior**

No horizontal scrollbars and no black border on the right of the sidebar.

**Screenshots**

<img width="302" alt="Screenshot 2024-06-19 at 9 29 20 PM" src="https://github.com/WordPress/wporg-theme-directory/assets/272444/fbd4fd9f-8f45-4038-b0c9-8f3ead145d27">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari or Chrome

**Comment by ryelle** [comment]
Thanks for flagging the scrollbar issue :)

> Also, a black border is visible at the right of the sidebar which seems unnecessary.

The off-black border is there for separation when in the loading state, or viewing a theme with a dark color scheme.

| Loading | Dark colors |
|---|---|
| ![loading](https://github.com/WordPress/wporg-theme-directory/assets/541093/28860980-ce3d-4cea-b311-11d2f11c0c33) | ![dark](https://github.com/WordPress/wporg-theme-directory/assets/541093/0820758b-12e2-4e3f-95bf-d96c1fec9b5c) |

**Comment by youknowriad** [comment]
Thanks for the quick fix. 

How do releases work? When does the site get updated?

**Comment by ryelle** [comment]
It should be updated already — it's a manual deployment from a sandbox, but I pushed it right after that commit.

**Comment by youknowriad** [comment]
Mmm, I'm actually still seeing the horizontal scrollbars using the link in the issue.

**Comment by ryelle** [comment]
You are correct… looks like the version isn't set correctly so it's serving the old CSS.

**Comment by ryelle** [comment]
Fixed the version string so it should be serving the correct CSS now.

**Comment by youknowriad** [comment]
Great. Thank you :)
